version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessário para monitorar alterações no Docker
      - WATCHPACK_POLLING=true   # Adicional para Webpack no hot reload
      - NODE_ENV=development     # Garante que o ambiente é de desenvolvimento
