services:
  bitcoin-regtest:
    image: bitcoin/bitcoin
    container_name: bitcoin-regtest
    command: ["bitcoind", "-datadir=/root/.bitcoin", "-regtest", "-server=1", "-rpcallowip=0.0.0.0/0", "-rpcbind=0.0.0.0", "-rpcuser=user", "-rpcpassword=pass", "-txindex=1", "-printtoconsole"]
    ports:
      - 18443:18443
      - 18444:18444
    volumes:
      - ./api/bitcoin-data:/root/.bitcoin # Criei um volume persistente
      - ./api/init.sh:/init.sh # Script de inicialização
    #entrypoint: ["/bin/bash", "-c", "sleep 10 && /init.sh"]
    restart: unless-stopped

  doidos-descentralizados-api:
    build:
      context: ./api
    container_name: doidos-descentralizados-api
    ports:
      - 5000:5000
    environment:
      - RPC_USER=user
      - RPC_PASSWORD=pass
      - RPC_HOST=bitcoin-regtest
      - RPC_PORT=18443
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - bitcoin-regtest
    restart: unless-stopped

  doidos-descentralizados-app:
    build:
      context: ./doidos-descentralizados-app
      dockerfile: ./Dockerfile
    container_name: doidos-descentralizados-app    
    ports:
      - "3000:3000" # Porta exposta pelo container
    volumes:
      - ./doidos-descentralizados-app/:/usr/src/app # Mapeamento para desenvolvimento local
      - /usr/src/app/node_modules # Evita conflitos com o host
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessário para monitorar alterações no Docker
      - WATCHPACK_POLLING=true   # Adicional para Webpack no hot reload
      - NODE_ENV=development     # Garante que o ambiente é de desenvolvimento
    depends_on:
      - doidos-descentralizados-api
